import { useShallow } from 'zustand/react/shallow'
import { useChatStore } from '../../store/chat-store'

export function useWorkbenchChatStoreState() {
  return useChatStore(
    useShallow((s) => ({
      threads: s.threads,
      threadSearch: s.threadSearch,
      showArchivedThreads: s.showArchivedThreads,
      activeThreadId: s.activeThreadId,
      activeThreadRelation: s.activeThreadRelation,
      activeThreadParentId: s.activeThreadParentId,
      selectThread: s.selectThread,
      createThread: s.createThread,
      createConversation: s.createConversation,
      blocks: s.blocks,
      liveReasoning: s.liveReasoning,
      liveAssistant: s.liveAssistant,
      error: s.error,
      runtimeErrorDetail: s.runtimeErrorDetail,
      runtimeStatus: s.runtimeStatus,
      busy: s.busy,
      route: s.route,
      pluginHostRoute: s.pluginHostRoute,
      workspaceRoot: s.workspaceRoot,
      conversationWorkspaceRoot: s.conversationWorkspaceRoot,
      runtimeConnection: s.runtimeConnection,
      setRoute: s.setRoute,
      openCode: s.openCode,
      openWrite: s.openWrite,
      openDesign: s.openDesign,
      clearActiveThreadSelection: s.clearActiveThreadSelection,
      ensureWriteThreadForWorkspace: s.ensureWriteThreadForWorkspace,
      ensureDesignThreadForWorkspace: s.ensureDesignThreadForWorkspace,
      createWriteThread: s.createWriteThread,
      createDesignThread: s.createDesignThread,
      openSettings: s.openSettings,
      openPlugins: s.openPlugins,
      openExperts: s.openExperts,
      openClaw: s.openClaw,
      openSchedule: s.openSchedule,
      openWorkflow: s.openWorkflow,
      chooseWorkspace: s.chooseWorkspace,
      clawChannels: s.clawChannels,
      activeClawChannelId: s.activeClawChannelId,
      selectClawChannel: s.selectClawChannel,
      resetClawChannelSession: s.resetClawChannelSession,
      setClawChannelModel: s.setClawChannelModel,
      appendLocalClawTurn: s.appendLocalClawTurn,
      setError: s.setError,
      sendMessage: s.sendMessage,
      reviewActiveThread: s.reviewActiveThread,
      queuedMessages: s.queuedMessages,
      removeQueuedMessage: s.removeQueuedMessage,
      interrupt: s.interrupt,
      probeRuntime: s.probeRuntime,
      composerModel: s.composerModel,
      composerProviderId: s.composerProviderId,
      composerPickList: s.composerPickList,
      composerModelGroups: s.composerModelGroups,
      disabledSkillIds: s.disabledSkillIds,
      composerMode: s.composerMode,
      setComposerMode: s.setComposerMode,
      setComposerModel: s.setComposerModel,
      setThreadSearch: s.setThreadSearch,
      renameThread: s.renameThread,
      pinThread: s.pinThread,
      archiveThread: s.archiveThread,
      deleteThread: s.deleteThread,
      spawnSideConversation: s.spawnSideConversation,
      openSideConversationDraft: s.openSideConversationDraft,
      selectSideConversation: s.selectSideConversation,
      setSidePanelOpen: s.setSidePanelOpen,
      sideConversations: s.sideConversations,
      sidePanel: s.sidePanel
    }))
  )
}
